// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	DeleteOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) error
	GetOrderByID(ctx context.Context, id uuid.UUID) (PurchaseOrder, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]PurchaseOrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]PurchaseOrder, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
