// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateVendor(ctx context.Context, arg CreateVendorParams) error
	DeleteCustomer(ctx context.Context, id uuid.UUID) error
	DeleteVendor(ctx context.Context, id uuid.UUID) error
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	GetVendorByEmail(ctx context.Context, email string) (Vendor, error)
	GetVendorByID(ctx context.Context, id uuid.UUID) (Vendor, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) error
}

var _ Querier = (*Queries)(nil)
