// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createVendor = `-- name: CreateVendor :exec
INSERT INTO vendors (id, name, email, phone, address, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVendorParams struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) error {
	_, err := q.db.ExecContext(ctx, createVendor,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors
WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendor, id)
	return err
}

const getVendorByEmail = `-- name: GetVendorByEmail :one
SELECT id, name, email, phone, address, created_at, updated_at
FROM vendors
WHERE email = $1
`

func (q *Queries) GetVendorByEmail(ctx context.Context, email string) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByEmail, email)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, name, email, phone, address, created_at, updated_at
FROM vendors
WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, name, email, phone, address, created_at, updated_at
FROM vendors
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVendorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listVendors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :exec
UPDATE vendors
SET name = $2,
    email = $3,
    phone = $4,
    address = $5,
    updated_at = $6
WHERE id = $1
`

type UpdateVendorParams struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) error {
	_, err := q.db.ExecContext(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.UpdatedAt,
	)
	return err
}
