// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO sales_orders (id, customer_id, status, total_amount, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrderParams struct {
	ID          uuid.UUID `json:"id"`
	CustomerID  uuid.UUID `json:"customer_id"`
	Status      string    `json:"status"`
	TotalAmount string    `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.Status,
		arg.TotalAmount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, status, total_amount, created_at, updated_at
FROM sales_orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, customer_id, status, total_amount, created_at, updated_at
FROM sales_orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]SalesOrder, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE sales_orders
SET customer_id = $2,
    status = $3,
    total_amount = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateOrderParams struct {
	ID          uuid.UUID `json:"id"`
	CustomerID  uuid.UUID `json:"customer_id"`
	Status      string    `json:"status"`
	TotalAmount string    `json:"total_amount"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder,
		arg.ID,
		arg.CustomerID,
		arg.Status,
		arg.TotalAmount,
		arg.UpdatedAt,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE sales_orders
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
