// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :exec
INSERT INTO items (id, name, description, sku, unit_price, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateItemParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Sku         string         `json:"sku"`
	UnitPrice   string         `json:"unit_price"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Sku,
		arg.UnitPrice,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, description, sku, unit_price, created_at, updated_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Sku,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemBySKU = `-- name: GetItemBySKU :one
SELECT id, name, description, sku, unit_price, created_at, updated_at
FROM items
WHERE sku = $1
`

func (q *Queries) GetItemBySKU(ctx context.Context, sku string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemBySKU, sku)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Sku,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, description, sku, unit_price, created_at, updated_at
FROM items
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Sku,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items
SET name = $2,
    description = $3,
    sku = $4,
    unit_price = $5,
    updated_at = $6
WHERE id = $1
`

type UpdateItemParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Sku         string         `json:"sku"`
	UnitPrice   string         `json:"unit_price"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Sku,
		arg.UnitPrice,
		arg.UpdatedAt,
	)
	return err
}
