// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdjustStock(ctx context.Context, arg AdjustStockParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) error
	CreateStock(ctx context.Context, arg CreateStockParams) error
	DeleteItem(ctx context.Context, id uuid.UUID) error
	GetItemByID(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemBySKU(ctx context.Context, sku string) (Item, error)
	GetStockByItemID(ctx context.Context, itemID uuid.UUID) (Stock, error)
	GetStockQuantityForUpdate(ctx context.Context, itemID uuid.UUID) (int32, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
	UpdateStock(ctx context.Context, arg UpdateStockParams) error
}

var _ Querier = (*Queries)(nil)
