// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adjustStock = `-- name: AdjustStock :exec
UPDATE stock
SET quantity = quantity + $2,
    updated_at = CURRENT_TIMESTAMP
WHERE item_id = $1
`

type AdjustStockParams struct {
	ItemID   uuid.UUID `json:"item_id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) AdjustStock(ctx context.Context, arg AdjustStockParams) error {
	_, err := q.db.ExecContext(ctx, adjustStock, arg.ItemID, arg.Quantity)
	return err
}

const createStock = `-- name: CreateStock :exec
INSERT INTO stock (id, item_id, quantity, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateStockParams struct {
	ID        uuid.UUID `json:"id"`
	ItemID    uuid.UUID `json:"item_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) error {
	_, err := q.db.ExecContext(ctx, createStock,
		arg.ID,
		arg.ItemID,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getStockByItemID = `-- name: GetStockByItemID :one
SELECT id, item_id, quantity, created_at, updated_at
FROM stock
WHERE item_id = $1
`

func (q *Queries) GetStockByItemID(ctx context.Context, itemID uuid.UUID) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByItemID, itemID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockQuantityForUpdate = `-- name: GetStockQuantityForUpdate :one
SELECT quantity FROM stock WHERE item_id = $1 FOR UPDATE
`

func (q *Queries) GetStockQuantityForUpdate(ctx context.Context, itemID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getStockQuantityForUpdate, itemID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const updateStock = `-- name: UpdateStock :exec
UPDATE stock
SET quantity = $2,
    updated_at = $3
WHERE item_id = $1
`

type UpdateStockParams struct {
	ItemID    uuid.UUID `json:"item_id"`
	Quantity  int32     `json:"quantity"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.ExecContext(ctx, updateStock, arg.ItemID, arg.Quantity, arg.UpdatedAt)
	return err
}
